## 빅데이터 기반 AI 응용 솔루션 개발자 전문과정

#### 교과목명 : Python 분석라이브러리 활용

- 평가일 : 21.7.23
- 성명 : 
- 점수 :

### Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열을 아래와 같이 생성하세요.
[0 1 2 3 4 5 6 7 8 9]  

[[0 1 2 3 4]  
 [5 6 7 8 9]]  
 
[[[0 1 2 3 4]  
  [5 6 7 8 9]]]

In [ ]:
# A.
import numpy as np
ar = np.arange(10)
ar1 = ar.reshape(-1,)
ar2 = ar.reshape(2,-1)
ar3 = ar.reshape(-1,2,5)
print(ar1)
print(ar2)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


### Q2. 1 ~ 100 까지 배열에서 3과 7의 공배수인 것만을 출력하세요.

In [ ]:
# A.
import numpy as np
a1 = np.arange(1, 101)
a1 = a1[(a1 % 3 ==0) & (a1 % 7==0)]
a1

array([21, 42, 63, 84])

### Q3. 아래 3차원 배열을 생성하여 출력한 후 1차원으로 변환하여 출력하세요.(reshape() 사용)

[[[ 0  1  2  3  4]  
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]  
   [15 16 17 18 19]]

 [[20 21 22 23 24]  
   [25 26 27 28 29]]]

In [ ]:
# A.
arr3d = np.arange(30).reshape(3,2,5)
print(arr3d)
arr1d = arr3d.reshape(-1,)
arr1d

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

### Q4. array2d에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.
arr2d = np.arange(1,10).reshape(3,3)

[3, 6]  

[[1, 2],  
[4, 5]]

[[1, 2, 3]  
[4, 5, 6]]

In [ ]:
# A.
arr2d = np.arange(1,10).reshape(3,3)
print(arr2d)
print(arr2d[[0,1],2])
print(arr2d[[0,1],0:2])
print(arr2d[[0,1],:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


### Q5. 아래 두행렬을 np.arange, reshape를 이용해서 생성 각각 a1, b1으로 저장하고 행렬 내적을 계산한 결과를 출력하세요.

[[1 2 3]  
 [4 5 6]  
 [7 8 9]]

[[10 11 12]  
 [13 14 15]  
 [16 17 18]]

In [ ]:
# A.
import numpy as np
a = np.arange(1, 10).reshape(3,3)
b = np.arange(10, 19).reshape(3,3)
ab_product = np.dot(a,b)
print(a,'\n')
print(b,'\n')
print(ab_product)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[10 11 12]
 [13 14 15]
 [16 17 18]] 

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


### Q6. ar의 역행렬을 출력하고 검증을 수행하세요.

In [ ]:
np.random.seed(1)
ar = np.random.randint(1,4,size=(3,3))
ar

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [ ]:
# A.
rar = np.linalg.inv(ar)
print(rar,'\n')
np.dot(ar,rar)

[[-3.33066907e-16  1.00000000e+00 -1.00000000e+00]
 [-1.00000000e+00  1.00000000e+00 -1.48029737e-16]
 [ 2.00000000e+00 -3.00000000e+00  2.00000000e+00]] 



array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00, -4.4408921e-16],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

### Q7. 10 ~ 20 사이의 정수 난수로 10행 5열 2차원 배열을 생성하고 저장한 후 다시 불러내서 출력하세요.

In [ ]:
# A.
import numpy as np
import pandas as pd
np.random.seed(0)
ar = np.random.randint(10,20,size=(10,5))
np.save('ar_test',ar)
np.load('ar_test.npy')

array([[15, 10, 13, 13, 17],
       [19, 13, 15, 12, 14],
       [17, 16, 18, 18, 11],
       [16, 17, 17, 18, 11],
       [15, 19, 18, 19, 14],
       [13, 10, 13, 15, 10],
       [12, 13, 18, 11, 13],
       [13, 13, 17, 10, 11],
       [19, 19, 10, 14, 17],
       [13, 12, 17, 12, 10]])

### Q8. df = sns.load_dataset('titanic')로 불러와서 다음 작업을 수행한 후 출력하세요.
- 전체 칼럼중 'survived'외에 모든 칼럼을 포함한 df_x를 산출한 후 dataset/df_x.pkl로 저장한다.
- df_x.pkl을 데이터프레임 df_x 이름으로 불러온 후 앞 5개 행을 출력한다. 

In [ ]:
# A.
import seaborn as sns
import pandas as pd

# titanic 데이터셋 가져오기
df = sns.load_dataset('titanic')
df_x = df.drop('survived',axis=1)
df_x.to_pickle('dataset/df_x.pkl')
df_x = pd.read_pickle('dataset/df_x.pkl')
df_x.head()

pclass     sex   age  sibsp  parch     fare embarked  class    who  \
0       3    male  22.0      1      0   7.2500        S  Third    man   
1       1  female  38.0      1      0  71.2833        C  First  woman   
2       3  female  26.0      0      0   7.9250        S  Third  woman   
3       1  female  35.0      1      0  53.1000        S  First  woman   
4       3    male  35.0      0      0   8.0500        S  Third    man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True  
3       False    C  Southampton   yes  False  
4        True  NaN  Southampton    no   True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### Q9. df = sns.load_dataset('titanic')로 불러와서 deck 열에서 NaN 갯수를 계산하세요.

In [ ]:
# A.
# deck 열의 NaN 개수 계산하기
df = sns.load_dataset('titanic')
print(df['deck'].isnull().sum(axis=0))

688


### Q10. Q9의 df에서 각 칼럼별 null 개수와 df 전체의 null 개수를 구하세요.

In [ ]:
# A.
# 각 칼럼별 null 개수
print(df.isnull().sum())
print()
print(df.isnull().sum(axis=0).sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

869


### 아래 tdf 데이터프레임에서 Q11 ~ Q12 작업을 수행하세요.

In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

survived     sex   age  class
0         0    male  22.0  Third
1         1  female  38.0  First
2         1  female  26.0  Third
3         1  female  35.0  First
4         0    male  35.0  Third

### Q11. age를 7개 카테고리로 구분하는 새로운 칼럼 'cat_age'를 생성하여 출력하세요. 단, 카테고리 구분을 수행하는 사용자 함수를 만들고 그 함수를 age 칼럼에 매핑하여 결과를 tdf1에 저장하고 출력하세요.

[카테고리]  
age <= 5: cat = 'Baby'  
age <= 12: cat = 'Child'  
age <= 18: cat = 'Teenager'  
age <= 25: cat = 'Student'  
age <= 60: cat = 'Adult'  
age > 60 : cat = 'Elderly'

In [ ]:
# A.
def cat_age(x):
    cat = ''
    if x <= 5: cat = 'Baby'
    elif x <= 12: cat = 'Child'
    elif x <= 18: cat = 'Teenager'
    elif x <= 25: cat = 'Student'
    elif x <= 35: cat = 'Young Adult'
    elif x <= 60: cat = 'Adult'
    else : cat = 'Elderly'
    
    return cat

tdf1 = tdf.copy()    
tdf1['age_cat'] = tdf.age.apply(cat_age)

tdf1.head()

survived     sex   age  class      age_cat
0         0    male  22.0  Third      Student
1         1  female  38.0  First        Adult
2         1  female  26.0  Third  Young Adult
3         1  female  35.0  First  Young Adult
4         0    male  35.0  Third  Young Adult

### Q12.  tdf1의 sex, class 칼럼을 '_'으로 연결한 'sc'칼럼을 추가한 후 아래와 같이 출력하세요.



In [ ]:
# 출력 결과     


In [ ]:
# A.

tdf1['sc'] = tdf1[['sex','class']].agg('_'.join,axis=1)
tdf1.head()

survived     sex   age  class      age_cat            sc
0         0    male  22.0  Third      Student    male_Third
1         1  female  38.0  First        Adult  female_First
2         1  female  26.0  Third  Young Adult  female_Third
3         1  female  35.0  First  Young Adult  female_First
4         0    male  35.0  Third  Young Adult    male_Third

### Q13. join() 메소드는 두 데이터프레임의 행 인덱스를 기준으로 결합한다. 2개의 주식데이터를 가져와서 join() 메소드로 아래와 같이 결합한 후 다음 사항을 수행하세요.
- df1과 df2의 교집합만 출력되도록 결합하여 df4에 저장하고 출력
- df4에서 중복된 칼럼을 삭제한 후 블린 인덱싱을 이용하여 eps가 3000 보다 적거나 stock_name이 이마트인 데이터를 선택하여 데이터프레임을 생성하고 df5 이름으로 저장 및 출력하세요.(단, '<' 와 '==' 를 반드시 사용해야 함)

In [ ]:
# A.

df1 = pd.read_excel('drive/MyDrive/cakd3_lecturer/강의/library/pandas/dataset/stock price.xlsx', index_col='id')
df2 = pd.read_excel('drive/MyDrive/cakd3_lecturer/강의/library/pandas//dataset/stock valuation.xlsx', index_col='id')
df4 = df1.join(df2, how='inner')
print(df4)
print()
df4.drop('name', axis=1, inplace=True)

df5 = df4[(df4['eps'] < 3000) | (df4['stock_name'] == '이마트')]
df5

       stock_name          value   price  ...     bps        per       pbr
id                                        ...                             
130960     CJ E&M   58540.666667   98900  ...   54068  15.695091  1.829178
139480        이마트  239230.833333  254500  ...  295780  13.931338  0.860437
145990        삼양사   82750.000000   82000  ...  108090  14.283226  0.758627
185750        종근당   40293.666667  100500  ...   40684  25.185866  2.470259
204210     모두투어리츠    3093.333333    3475  ...    5335  40.802348  0.651359

[5 rows x 8 columns]



stock_name          value   price  ...     bps        per       pbr
id                                        ...                             
139480        이마트  239230.833333  254500  ...  295780  13.931338  0.860437
204210     모두투어리츠    3093.333333    3475  ...    5335  40.802348  0.651359

[2 rows x 7 columns]

### Q14. 아래 df에서 drop_duplicates() 메소드를 사용하여 c4, c5열을 기준으로 중복 행을 제거한 후 df3에 저장하고 출력하세요.

In [ ]:
# 중복 데이터를 갖는 데이터프레임 만들기
import pandas as pd
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2],
                  'c4':[1, 1, 1, 2, 3],
                  'c5':[1, 1, 2, 2, 5]})
print(df)

  c1  c2  c3  c4  c5
0  a   1   1   1   1
1  a   1   1   1   1
2  b   1   2   1   2
3  a   2   2   2   2
4  b   2   2   3   5


In [ ]:
# A.
# c2, c3열을 기준으로 중복 행을 제거  
df3 = df.drop_duplicates(subset=['c4', 'c5'])
print(df3)

  c1  c2  c3  c4  c5
0  a   1   1   1   1
2  b   1   2   1   2
3  a   2   2   2   2
4  b   2   2   3   5


### Q15. 'mpg'를 'kpl' 로 환산하여 새로운 열을 생성하고 반올림하여 소수점 아래 둘째 자리까지 처음 5개행을 출력하세요.

In [ ]:
# read_csv() 함수로 df 생성
import pandas as pd
auto_df = pd.read_csv('drive/MyDrive/cakd3_lecturer/강의/library/pandas/dataset/auto-mpg.csv')
# 열 이름을 지정
auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
print(auto_df.head(3)) 


    mpg  cylinders  displacement  ... model year  origin                       name
0  18.0          8         307.0  ...         70       1  chevrolet chevelle malibu
1  15.0          8         350.0  ...         70       1          buick skylark 320
2  18.0          8         318.0  ...         70       1         plymouth satellite

[3 rows x 9 columns]


In [ ]:
# A.
# mpg(mile per gallon)를 kpl(kilometer per liter)로 변환 (mpg_to_kpl = 0.425)
mpg_to_kpl = 1.60934 / 3.78541

# mpg 열에 0.425를 곱한 결과를 새로운 열(kpl)에 추가
auto_df['kpl'] = auto_df['mpg'] * mpg_to_kpl
print(auto_df.head(3))    
print('\n')

# kpl 열을 소수점 아래 둘째 자리에서 반올림 
auto_df['kpl'] = auto_df['kpl'].round(2)
print(auto_df.head(3))     

    mpg  cylinders  displacement  ... origin                       name       kpl
0  18.0          8         307.0  ...      1  chevrolet chevelle malibu  7.652571
1  15.0          8         350.0  ...      1          buick skylark 320  6.377143
2  18.0          8         318.0  ...      1         plymouth satellite  7.652571

[3 rows x 10 columns]


    mpg  cylinders  displacement  ... origin                       name   kpl
0  18.0          8         307.0  ...      1  chevrolet chevelle malibu  7.65
1  15.0          8         350.0  ...      1          buick skylark 320  6.38
2  18.0          8         318.0  ...      1         plymouth satellite  7.65

[3 rows x 10 columns]


### Q16. './dataset/stock-data.csv'를 데이터프레임으로 불러와서 datetime64 자료형으로 변환한 후에 년, 월, 일로 분리하고 year를 인덱스로 셋팅하여 출력하세요.

In [ ]:
# A.
# 날짜 데이터 분리

import pandas as pd

# read_csv() 함수로 파일 읽어와서 df로 변환
df = pd.read_csv('drive/MyDrive/cakd3_lecturer/강의/library/pandas/dataset/stock-data.csv')

# 문자열인 날짜 데이터를 판다스 Timestamp로 변환
df['new_Date'] = pd.to_datetime(df['Date'])   #df에 새로운 열로 추가
df.drop('Date',axis=1,inplace=True)

# dt 속성을 이용하여 new_Date 열의 년월일 정보를 년, 월, 일로 구분
df['Year'] = df['new_Date'].dt.year
df['Month'] = df['new_Date'].dt.month
df['Day'] = df['new_Date'].dt.day
df.set_index('Year',inplace=True)
df.head()

Close  Start   High    Low  Volume   new_Date  Month  Day
Year                                                           
2018  10100  10850  10900  10000  137977 2018-07-02      7    2
2018  10700  10550  10900   9990  170253 2018-06-29      6   29
2018  10400  10900  10950  10150  155769 2018-06-28      6   28
2018  10900  10800  11050  10500  133548 2018-06-27      6   27
2018  10800  10900  11000  10700   63039 2018-06-26      6   26

### Q17. titanic 데이터셋에서 5개 열을 선택해서 class열을 기준으로 그룹화를 수행한 후 아래와 같이 출력하였다. 다음 사항을 출력하세요.
5개 열 : ['age','sex', 'class', 'fare', 'survived']  
- 그룹별 평균 출력
- 그룹별 최대값 출력

In [ ]:
# A.
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

print(df.head())
print()
# class 열을 기준으로 분할(1개 열을 기준)
grouped = df.groupby(['class'])
print('그룹별 평균')
average = grouped.mean()
print(average)
print()
print('그룹별 최대값')
stat = grouped.max()
print(stat)

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

그룹별 평균
              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

그룹별 최대값
         age   sex      fare  survived
class                                 
First   80.0  male  512.3292         1
Second  70.0  male   73.5000         1
Third   74.0  male   69.5500         1


### Q18. titanic 데이터셋에서 'Third'그룹만을 선택해서 group3 이름으로 저장하고 통계요약표를 출력하세요.

In [ ]:
# A.
# 개별 그룹 선택하기
group3 = grouped.get_group('Third')
group3.describe()

age        fare    survived
count  355.000000  491.000000  491.000000
mean    25.140620   13.675550    0.242363
std     12.495398   11.778142    0.428949
min      0.420000    0.000000    0.000000
25%     18.000000    7.750000    0.000000
50%     24.000000    8.050000    0.000000
75%     32.000000   15.500000    0.000000
max     74.000000   69.550000    1.000000

### Q19. titanic 데이터셋에서 class 열, sex열 기준으로 그룹화한 후 그룹별 평균과 표준편차를 구하세요.

In [ ]:
# A.
grouped = df.groupby(['class', 'sex']) 
gdf = grouped.mean()
print(gdf)
print()
gdf = grouped.std()
print(gdf)

                     age        fare  survived
class  sex                                    
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447

                     age       fare  survived
class  sex                                   
First  female  13.612052  74.259988  0.176716
       male    15.139570  77.548021  0.484484
Second female  12.872702  10.891796  0.271448
       male    14.793894  14.922235  0.365882
Third  female  12.729964  11.690314  0.501745
       male    12.159514  11.681696  0.342694


In [ ]:
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

### Q20.  titanic 데이터셋에서 다음 전처리를 수행하세요.
1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 
2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.
3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 
4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 
5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [ ]:
df.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [ ]:
# A-1.
df.columns
df1 = df[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'deck']]
df1.head()

survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [ ]:
df1.isnull().sum()

survived      0
pclass        0
sex           0
age         177
sibsp         0
parch         0
fare          0
embarked      2
deck        688
dtype: int64

In [ ]:
# A-2.
df2 = df1.drop('deck',axis=1)
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
# A-3.
df2.age.isnull().sum()
df2.age.fillna(df2.age.mean(),inplace=True)
df2.age.isnull().sum()

0

In [ ]:
# A-4.
df2.embarked.isnull().sum()
df2.embarked.fillna(method='ffill',inplace=True)
df2.embarked.isnull().sum()

0

In [ ]:
# A5.
from sklearn import preprocessing

features = ['sex','embarked']
for feature in features:
    le = preprocessing.LabelEncoder()
    df2[feature] = le.fit_transform(df2[feature])
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    int64  
 3   age       891 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  891 non-null    int64  
dtypes: float64(2), int64(6)
memory usage: 55.8 KB
