In [1]:
#1
import numpy as np
ar1 = np.arange(10)
ar2 = np.arange(10).reshape(2,5)
ar3 = np.arange(10).reshape(1,2,5)
print(ar1)
print(ar2)
print(ar3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[[0 1 2 3 4]
  [5 6 7 8 9]]]


In [2]:
#2
import numpy as np
ar = np.arange(1,101)
ar[(ar%3==0) & (ar%7==0)]

array([21, 42, 63, 84])

In [3]:
#3
import numpy as np
ar = np.arange(10).reshape(1,2,5)
ar2 = np.arange(10,20).reshape(1,2,5)
ar3 = np.arange(20,30).reshape(1,2,5)

n_ar = ar.reshape(-1)
n_ar2 = ar2.reshape(-1)
n_ar3 = ar3.reshape(-1)

In [4]:
#4
import numpy as np
arr2d = np.arange(1,10).reshape(3,3)
arr2d
a1 = arr2d[:2,2:].reshape(-1).tolist()
a2 = arr2d[:2,:2].reshape(2,2).tolist()
a3 = arr2d[:2,].reshape(2,3).tolist()

In [5]:
#5
import numpy as np
a1 = np.arange(1,10).reshape(3,3)
b1 = np.arange(10,19).reshape(3,3)
a1.dot(b1)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [17]:
#6          X
import numpy as np
np.random.seed(1)
ar = np.random.randint(1,4,size=(3,3))
ar

array([[2, 1, 1],
       [2, 2, 1],
       [1, 2, 1]])

In [20]:
rar = np.linalg.inv(ar)
rar

array([[-1.11022302e-16,  1.00000000e+00, -1.00000000e+00],
       [-1.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 2.00000000e+00, -3.00000000e+00,  2.00000000e+00]])

In [21]:
check = ar.dot(rar)
check

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [-4.4408921e-16,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  0.0000000e+00,  1.0000000e+00]])

In [26]:
#7             X
import numpy as np
ar = np.random.randint(10,20,size=(10,5))
np.save('data',ar)
np.load('data.npy')

array([[13, 12, 14, 14, 10],
       [13, 13, 18, 13, 15],
       [16, 17, 15, 11, 17],
       [10, 12, 18, 12, 11],
       [14, 10, 14, 11, 17],
       [13, 11, 16, 16, 19],
       [16, 19, 16, 10, 10],
       [12, 19, 16, 10, 16],
       [17, 10, 13, 19, 10],
       [13, 14, 17, 15, 13]])

In [ ]:
#8
import seaborn as sns
import pandas as pd
df =sns.load_dataset('titanic')
df.columns
new_columns = ['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone']
df_x = df[new_columns]

df_x.to_pickle('df_x.pkl')
df_x = pd.read_pickle('df_x.pkl')

df_x.head()

In [ ]:
#9
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')
df['deck'].isnull().sum()

In [ ]:
#10
import pandas as pd
import seaborn as sns
print('각 컬럼별 null 개수', df.isnull().sum(),'\n')
print('df 전체 null 개수', df.isnull().sum().sum())

In [ ]:
#11
import pandas as pd
import seaborn as sns
df = sns.load_dataset('titanic')
tdf = df[['survived','sex','age','class']]
tdf.head()

def age_cat(x):
    cat = ''
    if x <= 5: 
        cat = 'Baby'
    elif x <= 12:
        cat = 'Child'
    elif x <= 18:
        cat = 'Teenager'
    elif x <= 25:
        cat = 'Student'
    elif x <= 60:
        cat = 'Adult'
    elif x > 60 :
        cat = 'Elderly'
    return cat
tdf1 = tdf.copy()

tdf1['age'] = tdf['age'].apply(lambda x : age_cat(x))
tdf1['age']
tdf1.head()

In [ ]:
#12
tdf1.info()
tdf1['class'] = tdf1['class'].astype('object')
tdf1['sc'] = tdf1['sex']+'_'+tdf1['class']
tdf1.head()

In [ ]:
#13
df1 = pd.read_excel('stock price.xlsx')
df2 = pd.read_excel('stock valuation.xlsx')
df4 = df1.merge(df2)
display(df4)
df4 = df4.drop('name',axis=1)
df5 = df4[ (df4['eps']< 3000) | (df4['stock_name']=='이마트')]
df5

In [ ]:
#14
import pandas as pd
df = pd.DataFrame({'c1':['a', 'a', 'b', 'a', 'b'],
                  'c2':[1, 1, 1, 2, 2],
                  'c3':[1, 1, 2, 2, 2],
                  'c4':[1, 1, 1, 2, 3],
                  'c5':[1, 1, 2, 2, 5]})
print(df)

df3 = df.drop_duplicates(subset=('c4','c5'),keep=False)
df3

In [ ]:
#15
import pandas as pd
auto_df = pd.read_csv('auto-mpg.csv')

auto_df.columns = ['mpg','cylinders','displacement','horsepower','weight',
              'acceleration','model year','origin','name'] 
print(auto_df.head(3)) 

mpg_to_kpl = 1.60934 / 3.78541

auto_df['kpl'] = auto_df['mpg'] * mpg_to_kpl
auto_df['kpl'] = auto_df['kpl'].round(2)

print(auto_df['kpl'])

In [ ]:
#16
import pandas as pd
import datetime as dt
import datetime
data = pd.read_csv('stock-data.csv')
data['Date'] = pd.to_datetime(data['Date']) 
data['Year'] = data['Date'].dt.year
data['Month'] = data['Date'].dt.month
data['Day'] = data['Date'].dt.day
data = data.set_index('Year')
data.head(1)

In [ ]:
#17
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
n_titanic = titanic[['age','sex', 'class', 'fare', 'survived']]
mean_grouped = n_titanic.groupby('class').mean()
max_grouped = n_titanic.groupby('class').max()

display('평균',mean_grouped)
display('최대값',max_grouped)

In [ ]:
#18
grouped = n_titanic.groupby('class')
group3 = grouped.get_group('Third')
display('Third',group3.describe())

In [ ]:
#19
mean_grouped = n_titanic.groupby(['class','sex']).mean()
std_grouped = n_titanic.groupby(['class','sex']).std()

display('평균',mean_grouped)
display('표준편차',std_grouped)

In [ ]:
#20
import seaborn as sns
df = sns.load_dataset('titanic')
df.head()

    1. df에서 중복 칼럼으로 고려할 수 있는 컬럼들(6개 내외)을 삭제한 후 나머지 컬럼들로 구성되는 데이터프레임을 df1 이름으로 저장 후 출력하세요. 

In [ ]:
# pclass , class / survived, alive / embarked , embark_town
df1 = df.drop(['class','alive','embark_town'],axis=1)
df1.head(1)

    2. df1에서 null값이 50% 이상인 칼럼을 삭제 후 df2 이름으로 저장하고 출력하세요.

In [ ]:
num_null = df1.isnull().sum() /len(df1) #deck column - 0.772166
df2 = df1.drop('deck',axis=1)
df2.head(1)

    3. df2에서 결측값이 있는 age 칼럼에 대해서 평균값으로 대체 처리를 수행하세요. 

In [ ]:
print(df2['age'].isnull().sum())
df2['age'] = df2['age'].fillna(df2['age'].mean())
df2['age'].isnull().sum()

    4. df2에서 결측값이 있는 embarked 칼럼에 대해서 앞행의 값으로 대체 처리를 수행하세요. 

In [ ]:
print(df2['embarked'].isnull().sum())
df2['embarked'] = df2['embarked'].fillna(method='ffill')
df2['embarked'].isnull().sum()

    5. df2 문자로 되어있는 칼럼들을 레이블 인코딩 수행하여 숫자로 변환 후 df2.info()를 출력하세요

In [ ]:
df2.head(1) # sex / who / adult_male/alone
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
features = ['sex','who','adult_male','alone']
for feature in features:
    df2[feature] = le.fit_transform(df2[feature])
df2.info()