#### NumPy
 'Numerical Python'의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공합니다.
 * Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
 * 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
 * 넘파이의 기본 데이터 타입은 ndarray, ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행합니다.


###### Numpy 특징
- 강력한 N 차원 배열 객체
- 정교한 브로드캐스팅(Brodacast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 푸리에 변환(Fouirier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [2]:
import numpy as np
data =np.random.randn(2,3) # 정규분포에서 2행 3열을 뽑는다. 
print(data)
print()
print(data * 10)
print()
print(data+data)

[[-0.77499606 -0.16354357 -0.06455204]
 [ 0.39901545 -1.58629316  0.50741295]]

[[ -7.7499606   -1.63543565  -0.64552036]
 [  3.99015447 -15.86293165   5.07412946]]

[[-1.54999212 -0.32708713 -0.12910407]
 [ 0.79803089 -3.17258633  1.01482589]]


다차원 배열

<img src='../Data/numpy차원.jpg' STYLE = 'width:500px;'>

In [3]:
data2 = [[1,2,3,4,],[5,6,7,8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
arr2 = np.arange(1,9).reshape(2,4)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
print(arr2.ndim)

2


In [9]:
#3차원 배열
array3 = np.array([[[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]],
                  [[1,2,3,4,5],[6,7,8,9,10]]])
print(array3.ndim)
print(array3.shape)

3
(3, 2, 5)


In [11]:
print(np.zeros(10))
print(np.zeros((3,6))) #3차원
print(np.zeros((2,3,2))) #

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [22]:
arr3 =np.arange(75)
# arr3 =np.arange(1,15)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74])

In [25]:
arr3.reshape(5,-1)
arr3.reshape(-1,15)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74]])

Q. 5행 3열, 7행 25열 다차원 배열을 생성하세요

In [30]:
arr1 = np.arange(15).reshape(5,3) # reshpae(5,-1)
arr1
arr2 = np.arange(7*25).reshape(7,25) #reshape(7,-1)
arr2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
         38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74],
       [ 75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
         88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
        138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174]])

Q. 1~30 연속된 정수로 1차원,2차원,3차원 배열을 생성하세요

In [47]:
arr = np.arange(1,31)
print(arr,'\n')
print(arr.reshape(3,10),'\n')
print(arr.reshape(2,3,5),'\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]] 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]] 



Q. 연속된 정수 1~20으로 1차원 배열을 생성한 후 2차원 3차원 배열로 변환시키세요

In [49]:
arr = np.arange(1,21)
print(arr,'1차원','\n')
print(arr.reshape(4,5),'2차원','\n')
print(arr.reshape(2,2,5),'3차원','\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] 1차원 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 2차원 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]] 3차원 



Q. 연속된 정수 1~30으로 2차원 배열을 생성한 후 1차원 3차원 배열로 변환시키세요

In [65]:
arr = np.arange(1,31).reshape(5,6)
print(arr,'2차원','\n')
print(arr.reshape(-1,),'1차원','\n') # 중요
print(arr.flatten(),'1차원','\n')
print(arr.reshape(2,3,5),'3차원','\n')

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]] 2차원 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 1차원 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30] 1차원 

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]] 3차원 



Q. 연속된 정수 1~24로 3차원 배열을 생성한 후 1차원 2차원 배열로 변환하세요

In [64]:
arr = np.arange(1,25).reshape(3,2,4)
print(arr,'3차원','\n')
print(arr.reshape(4,6),'2차원','\n')
print(arr.reshape(-1,),'1차원')

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]] 3차원 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]] 2차원 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] 1차원


In [69]:
#배열을 리스트로
ar3 = np.arange(30).reshape(5,3,2)
ar3.tolist()

[[[0, 1], [2, 3], [4, 5]],
 [[6, 7], [8, 9], [10, 11]],
 [[12, 13], [14, 15], [16, 17]],
 [[18, 19], [20, 21], [22, 23]],
 [[24, 25], [26, 27], [28, 29]]]

In [71]:
a = np.full((2,2),7) # 2행 2열 값은 모두 7
a

array([[7, 7],
       [7, 7]])

In [72]:
# 대각 행렬

In [73]:
ar = np.eye(3)
ar

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.zeros_like(a)
b

[[1 2 3]
 [4 5 6]]


array([[0, 0, 0],
       [0, 0, 0]])

In [76]:
#0~10을 균등하게 50개로 나눠줌
np.linspace(0,10)
np.linspace(0,1,5,restep=True)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [77]:
import matplotlib.pyplot as plt
x = np.linspace(0,1)
y = np.linspace(0,50)
