In [1]:
import numpy as np

In [5]:
#Boolen Indexing

In [10]:
ar1 = np.arange(1,10)
print(ar1)
print(ar1>5)
ar2 = ar1[ar1>5]
print(ar2)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [13]:
indexes = np.array([5,6,7,8])
ar3 = ar1[indexes]
ar3

array([6, 7, 8, 9])

Q. 1~14까지 ndarray를 만들어 array_e로 저장하고 (array_e / 2) >5 를 만족하는 불린 인덱스로 출력하세요

In [20]:
array_e = np.arange(1,15)
print(array_e)
find = (array_e/2) > 5
answer = array_e[find]
answer

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([11, 12, 13, 14])

In [19]:
find

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [50]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
data  = np.random.randn(7,4)
print(names,'\n')
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] 

[[-2.30017184e+00 -7.38240258e-01  9.45260885e-01  1.72286961e+00]
 [-7.59853876e-01  1.31660387e+00  1.17808546e+00 -1.06142149e+00]
 [-5.12079576e-01  1.24352454e+00  1.14017821e+00  1.14154015e+00]
 [ 3.01902501e-04  2.07261898e-01  3.13144128e-01 -2.72292989e-01]
 [ 3.92173080e-01 -3.44272471e-01 -4.56416380e-01 -9.95069810e-01]
 [ 1.80445095e+00  8.37773685e-01  1.02509336e+00 -1.38840468e+00]
 [ 6.39546544e-01 -1.47944644e-01  1.36291413e+00 -7.66510924e-01]]


In [51]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [52]:
data[names=='Bob']

array([[-2.30017184e+00, -7.38240258e-01,  9.45260885e-01,
         1.72286961e+00],
       [ 3.01902501e-04,  2.07261898e-01,  3.13144128e-01,
        -2.72292989e-01]])

In [53]:
data[names =='Bob',2:]

array([[ 0.94526089,  1.72286961],
       [ 0.31314413, -0.27229299]])

In [54]:
data[names != 'Bob']

array([[-0.75985388,  1.31660387,  1.17808546, -1.06142149],
       [-0.51207958,  1.24352454,  1.14017821,  1.14154015],
       [ 0.39217308, -0.34427247, -0.45641638, -0.99506981],
       [ 1.80445095,  0.83777369,  1.02509336, -1.38840468],
       [ 0.63954654, -0.14794464,  1.36291413, -0.76651092]])

In [55]:
mask = (names == 'Bob') | (names == 'Will')
data[mask]

array([[-2.30017184e+00, -7.38240258e-01,  9.45260885e-01,
         1.72286961e+00],
       [-5.12079576e-01,  1.24352454e+00,  1.14017821e+00,
         1.14154015e+00],
       [ 3.01902501e-04,  2.07261898e-01,  3.13144128e-01,
        -2.72292989e-01],
       [ 3.92173080e-01, -3.44272471e-01, -4.56416380e-01,
        -9.95069810e-01]])

In [56]:
data[data<0] = 0
data

array([[0.00000000e+00, 0.00000000e+00, 9.45260885e-01, 1.72286961e+00],
       [0.00000000e+00, 1.31660387e+00, 1.17808546e+00, 0.00000000e+00],
       [0.00000000e+00, 1.24352454e+00, 1.14017821e+00, 1.14154015e+00],
       [3.01902501e-04, 2.07261898e-01, 3.13144128e-01, 0.00000000e+00],
       [3.92173080e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.80445095e+00, 8.37773685e-01, 1.02509336e+00, 0.00000000e+00],
       [6.39546544e-01, 0.00000000e+00, 1.36291413e+00, 0.00000000e+00]])

In [57]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.31660387, 1.17808546, 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [1.80445095, 0.83777369, 1.02509336, 0.        ],
       [0.63954654, 0.        , 1.36291413, 0.        ]])

In [59]:
#배열의 전치와 축 바꾸기
ar = np.arange(15).reshape(3,5)
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
ar_t = ar.T

In [63]:
ar = ar_t.T
ar

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

6행 3열짜리 난수로 된

In [81]:
np.random.seed(0)
ar = np.random.randn(6,3)
ar

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826]])

In [83]:
ar = np.arange(1,101)

In [88]:
ans1 = ar[ar % 3 == 0]
ans2 = ar[(ar%3 == 0) | (ar%5 ==0)]
ans3 = ar[(ar%3 ==0) & (ar%5 == 0 )]

In [89]:
ar = np.random.randn(5,4)

In [90]:
#반올림
ar.mean().round(4)

0.0632

In [92]:
ar.sum().round(4)

1.2636

In [94]:
ar = np.arange(1,9)
print(ar,'\n')
ar.cumsum() #누적합계

[1 2 3 4 5 6 7 8] 



array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [96]:
ar =  np.arange(9).reshape(3,3)
print(ar,'\n')
ar.cumsum(axis=1)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 



array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

In [99]:
np.random.seed(0)
ar = np.random.randn(10)
print(ar,'\n')
(ar>0).sum()
len(ar[ar>0])

[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799 -0.97727788
  0.95008842 -0.15135721 -0.10321885  0.4105985 ] 



7

In [101]:
bools = np.array([False,False,True,True])
bools.any() # 요소 중 하나가 True인지

True

In [103]:
bools.all() # 요소 전체가 True인지

False

In [105]:
ar = np.random.randn(4,4)
print(ar)
np.where(ar>0,2,-2) # where( 조건, 맞을때 리턴값, 아닐때 리턴값)

[[ 0.04575852 -0.18718385  1.53277921  1.46935877]
 [ 0.15494743  0.37816252 -0.88778575 -1.98079647]
 [-0.34791215  0.15634897  1.23029068  1.20237985]
 [-0.38732682 -0.30230275 -1.04855297 -1.42001794]]


array([[ 2, -2,  2,  2],
       [ 2,  2, -2, -2],
       [-2,  2,  2,  2],
       [-2, -2, -2, -2]])