### Pandas
    - 판다스는 구조화 된 데이터 형식을 제공. Series = 1차원 배열. DataFrame = 2차원 배열.
    - 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. Series 와 DataFrame 대표적인 클래스 객체.
    - 시리즈 인덱스는 데이터 값과 1:1대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(dictionary)

* Contents
* Series(변환,인덱스 구조, 원소 선택)
* DataFrame(변환, 행인덱스/열이름 지정, 삭제, 선택, 추가, 변경, 전치 , 인덱스활용 )

* axis = 중심선. axis = 0 : Row / axis = 1 column


* When inplace = True , the data is modified in place, which means it will return nothing and the dataframe is now updated. When inplace = False , which is the default, then the operation is performed and it returns a copy of the object. You then need to save it to something.

#### Import pandas

In [1]:
import pandas as pd

#### Series class

In [2]:
# K : V 를 갖는 DICT 를 만들고 변수 dict_data 에 저장
dict_data = {'a':1,'b':2,'c':3}
srD = pd.Series(dict_data) #자동 index 설정
print(type(srD)) 
print(srD)

<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64


In [3]:
# LIST to Series
List_data = ['2019-07-02',3.14,'ABC',100,True]
srL = pd.Series(List_data,index=list('abcde')) # index 설정.    #list('문자열') - 문자열을 나눔.
print(type(srL))
print(srL)

print('\n')
# index / value
idx = srL.index
val = srL.values
print(idx)
print(val)

<class 'pandas.core.series.Series'>
a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object


Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-07-02' 3.14 'ABC' 100 True]


In [4]:
# Tuple to Seires
tup_data = ('Kevin','2021-07-07','남',True)
srT = pd.Series(tup_data, index = ['이름','생년월일','성별','학생여부'])
print(type(srT))
print(srT)
#open API json으로 불러왔을떈 DICT 포맷. --> Series/DataFrame변경가능
print('\n')

#indexing
print(srT[0])
print(srT['이름'])
print(srT[[1,2]]) #색인시 [[]]

<class 'pandas.core.series.Series'>
이름           Kevin
생년월일    2021-07-07
성별               남
학생여부          True
dtype: object


Kevin
Kevin
생년월일    2021-07-07
성별               남
dtype: object


#### Numpy

In [5]:
import numpy as np

npA = np.arange(11,16)
print(type(npA),npA) #numpy.ndarray
print('\n')

srA = pd.Series(npA)
print(type(srA),srA)
print('\n')

sL = npA.tolist()
print(type(sL),sL)

<class 'numpy.ndarray'> [11 12 13 14 15]


<class 'pandas.core.series.Series'> 0    11
1    12
2    13
3    14
4    15
dtype: int32


<class 'list'> [11, 12, 13, 14, 15]


Q.
       
    밑과 같이 출력하시오

In [6]:
Val = np.arange(1000,5000,1000)

Answer = pd.Series(Val , index=["California","Ohio","Oregon","Texas"], name="population")
Answer.index.name = 'state'
print(Answer)
print('\n')

Answer.California = np.nan
print(Answer)
print('\n')

print(Answer.isnull()) #결측치 확인
print('\n')
print(Answer.isnull().sum()) # True = 1 , False = 0

state
California    1000
Ohio          2000
Oregon        3000
Texas         4000
Name: population, dtype: int32


state
California       NaN
Ohio          2000.0
Oregon        3000.0
Texas         4000.0
Name: population, dtype: float64


state
California     True
Ohio          False
Oregon        False
Texas         False
Name: population, dtype: bool


1


#### DataFrame
    DataFrame은 2차원 배열, R의 DataFrame에서 유래.
    DataFrame의 열은 각각 시리즈 개체
    시리즈를 열벡터(col.vector)라고 하면 DataFrame은 여러개의 열벡터(col.vector)들이 같은 row.index를 기준으로
    줄지어 결합된 2차원 vector 또는 핼렬(metrix)라고 함
    선형대수학에서 열 벡터 (m x 1 행렬)는 m 원소들의 단일 열 행렬
    행 벡터 (1 x m 행렬)은 m 원소들의 단일 행 행렬.
    LIST, DICT, ndarry등 다양한 데이터로부터 생성됨.
    반대로 LIST, DICT, ndarry 등으로 변환 될 수 있음.

In [7]:
#Array to DataFrame
data = np.random.randint(100,120,size=(3,3)) #3행 3열 9개.
print(data,type(data))
df = pd.DataFrame(data,index=['d1','d2','d3'],columns =['pd','sales','inv'])
print('\n')
print(type(df))
df

[[110 108 115]
 [115 102 118]
 [107 115 111]] <class 'numpy.ndarray'>


<class 'pandas.core.frame.DataFrame'>


pd  sales  inv
d1  110    108  115
d2  115    102  118
d3  107    115  111

In [8]:
#pandas indexing : iloc 정수 인덱스, loc 이름 인덱스

np.random.seed(2) #안에는 아무거나 넣어도 됨.

print(df.iloc[1],'\n',type(df.iloc[1]),'\n') #Serues
print(df.loc['d2'],'\n',type(df.iloc[1]))
print('\n')

print(df.iloc[1][1])
print(df.loc['d2','sales'])

pd       115
sales    102
inv      118
Name: d2, dtype: int32 
 <class 'pandas.core.series.Series'> 

pd       115
sales    102
inv      118
Name: d2, dtype: int32 
 <class 'pandas.core.series.Series'>


102
102


In [9]:
df.loc[:,'inv']

d1    115
d2    118
d3    111
Name: inv, dtype: int32

In [10]:
id = np.arange(1,1001)
gender = np.random.randint(2,size=1000)
age = np.random.randint(1,100,size=1000)
region = np.random.randint(1,11,size=1000)

In [11]:
ID = pd.Series(id,name ='Id')
Gender = pd.Series(gender,name='Gender')
Age = pd.Series(age,name='Age')
Region = pd.Series(region,name='Region')

df = pd.concat([ID,Gender,Age,Region],axis=1,names = 'data')
# df.rename(columns={0:'ID',1:"Gender",2:"Age",3:"region"},inplace=True)


In [19]:
#2차원 리스트를 DataFrame으로 변환
# list1 = a.tolist()
a = np.random.randint(1,5,size=(10,5))
# print(a,type(a))
list1 = a.tolist()
print(list1,type(list1))

df1  = pd.DataFrame(list1,columns=['c1','c2','c3','c4','c5'])
print(df1)

[[4, 2, 1, 4, 3], [2, 3, 4, 2, 4], [2, 1, 1, 2, 2], [2, 4, 3, 4, 3], [1, 1, 3, 1, 3], [4, 1, 2, 1, 4], [4, 2, 1, 1, 3], [2, 3, 3, 4, 1], [1, 1, 3, 2, 3], [3, 2, 4, 2, 3]] <class 'list'>
   c1  c2  c3  c4  c5
0   4   2   1   4   3
1   2   3   4   2   4
2   2   1   1   2   2
3   2   4   3   4   3
4   1   1   3   1   3
5   4   1   2   1   4
6   4   2   1   1   3
7   2   3   3   4   1
8   1   1   3   2   3
9   3   2   4   2   3


In [31]:
# DataFrame을  Array, LIST, DICT로 변환
Ar = df1.values
print(Ar,type(Ar))
print()
Li = Ar.tolist()
print(Li,type(Li))
print()
DICT = df1.to_dict('list')
print(DICT,type(DICT))

[[4 2 1 4 3]
 [2 3 4 2 4]
 [2 1 1 2 2]
 [2 4 3 4 3]
 [1 1 3 1 3]
 [4 1 2 1 4]
 [4 2 1 1 3]
 [2 3 3 4 1]
 [1 1 3 2 3]
 [3 2 4 2 3]] <class 'numpy.ndarray'>

[[4, 2, 1, 4, 3], [2, 3, 4, 2, 4], [2, 1, 1, 2, 2], [2, 4, 3, 4, 3], [1, 1, 3, 1, 3], [4, 1, 2, 1, 4], [4, 2, 1, 1, 3], [2, 3, 3, 4, 1], [1, 1, 3, 2, 3], [3, 2, 4, 2, 3]] <class 'list'>

{'c1': [4, 2, 2, 2, 1, 4, 4, 2, 1, 3], 'c2': [2, 3, 1, 4, 1, 1, 2, 3, 1, 2], 'c3': [1, 4, 1, 3, 3, 2, 1, 3, 3, 4], 'c4': [4, 2, 2, 4, 1, 1, 1, 4, 2, 2], 'c5': [3, 4, 2, 3, 3, 4, 3, 1, 3, 3]} <class 'dict'>


In [33]:
#file 생성
file_data = pd.DataFrame({
    'col1':[1,2,3,4,5,6],
    'col2':['A','A','B','B','C','C']
})
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [36]:
#file data 저장
file_data.to_csv('../Data/file_data.csv',index=None)

In [38]:
#file 불러오기
file_data=pd.read_csv("../Data/file_data.csv")

In [40]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})

Q. df_1과 df_2를 행방향과 열방향으로 병합하세요.=

In [44]:
df_3 = pd.concat([df_1,df_2],axis=1)
df_4 = pd.concat([df_1,df_2])
print(df_3)
print()
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [60]:
#데이터 추출
print(df_4.col2)
print(df_4['col2'])
# pd.DataFrame(df_4['col2']
df_4[['col2','col1']]

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object
0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object


col2  col1
0    A     1
1    B     2
2    C     3
0    D     4
1    E     5
2    F     6

In [68]:
df = df1.copy()
df_dc_c = df.drop('c1',axis=1)
df_dc_c.head()

c2  c3  c4  c5
0   2   1   4   3
1   3   4   2   4
2   1   1   2   2
3   4   3   4   3
4   1   3   1   3

In [83]:
#query : 조회
df.query('index==0')
df.query('c3==3 & c4==2')
df.query('c3==2 | c4==2')

c1  c2  c3  c4  c5
1   2   3   4   2   4
2   2   1   1   2   2
5   4   1   2   1   4
8   1   1   3   2   3
9   3   2   4   2   3

In [85]:
#특정 열만 추출
df.query('c3==3')[['c3','c4']]

c3  c4
3   3   4
4   3   1
7   3   4
8   3   2

In [97]:
df.rename(columns = {'c1':'Korean','c2':'English','c3':'Math','c4':'Science','c5':'Society'},
          index={0:"A",1:"B",2:"C",3:"D",4:"E",5:"F",6:"G",7:"H",8:"I",9:"J"},inplace =True)
df

Korean  English  Math  Science  Society
A       4        2     1        4        3
B       2        3     4        2        4
C       2        1     1        2        2
D       2        4     3        4        3
E       1        1     3        1        3
F       4        1     2        1        4
G       4        2     1        1        3
H       2        3     3        4        1
I       1        1     3        2        3
J       3        2     4        2        3

In [98]:
# import Warnings
# warnings.filterwarnings('ignore')

In [103]:
df.loc['A','Society']
df.iloc[0,4]

3